name: Get & Cache Dependencies
description: Get the dependencies and cache them for future runs.
runs:
  using: "composite" # allows to define multiple steps in a single action
  steps:
    - name: Step 1 - Cache Dependencies
      id: cache_dependencies
      uses: actions/cache@v3
      with:
        path: node_modules # Путь к папке с зависимостями, которую нужно кэшировать
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }} # Ключ кэша, основанный на хэше package-lock.json
    - name: Step 2 - Install Dependencies
      if: steps.cache_dependencies.outputs.cache-hit != 'true' # Устанавливать зависимости только если кэш не найден
      shell: bash
      run: npm install # Команда для установки зависимостей, например, npm install для Node.js проектов