name: Run Local JavaScript Action

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  demo-javascript-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run local JavaScript action
        id: js_action
        uses: ./.github/workflows/any_javascript
        with:
          name: GitHub Actions

      - name: Show action output
        run: echo "Action returned time='${{ steps.js_action.outputs.time }}'"
