---
# .github/workflows/ci.yml (caller workflow)
name: CI
on:
  push:
    branches: [main]
jobs:
  any-call-reusable-build:
    uses: b-c-v/test/.github/workflows/reusable-build.yml@main
    with:
      node_version: "20"
      # environment: "production"  # optional - omit to use the default ("staging")
    secrets:
      npm_token: ${{ secrets.NPM_TOKEN }}